### ISSUE TITLE
Implement basic address book component

### ISSUE THREAD

**Issue by Isabello** [iov-one/iov-wallet#178]
Once we have added persistence to the application, we need to add the addressbook component in.

This will include:

- [ ] SendTx drop down to send by address
- [ ] Address Book component to see my contacts
- [ ] Address Book - Add contact  - Component
